core/urls.py
from django.urls import path

from . import views

app_name = 'enquete'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:questao_id>/', views.detalhes, name='detalhes'),
    path('<int:questao_id>/resultados/', views.resultados, name='resultados'),
    path('<int:questao_id>/vote/', views.vote, name='vote'),
    path('resultadodata/<str:obj>', views.resultadosData, name='resultadodata')
]

enquetes/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('enquete/', include('core.urls')),
    path('admin/', admin.site.urls),
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

core/models.py
from django.db import models


class Questao(models.Model):
    questao_texto = models.CharField(max_length=200)
    pub_data = models.DateTimeField('Data de publicação')

    def __str__(self):
        return self.questao_texto


class Choice(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pages/models.py
from django.db import models

# Create your models here.

core/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Questao, Choice

# Get questions and display them
def index(request):
    latest_question_list = Questao.objects.order_by('-pub_data')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

# Show specific question and choices
def detalhes(request, questao_id):
  try:
    questao = Questao.objects.get(pk=questao_id)
  except Questao.DoesNotExist:
    raise Http404("Question does not exist")
  return render(request, 'polls/detail.html', {'questao': questao})

# Get question and display results
def resultados(request, questao_id):
  questao = get_object_or_404(Questao, pk=questao_id)
  return render(request, 'polls/results.html', {'questao': questao})

# Vote for a question choice
def vote(request, questao_id):
    # print(request.POST['choice'])
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        selected_choice = questao.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': questao,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votos += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('enquete:resultados', args=(questao.id,)))

def resultadosData(request, obj):
    votodata = []

    questao = Questao.objects.get(id=obj)
    votos = questao.choice_set.all()

    for i in votos:
        votodata.append({i.choice_text: i.votos})
    return JsonResponse(votodata, safe=False)

pages/views.py
from django.shortcuts import render

def index(request):
  return render(request, 'pages/index.html')

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <title>Vote {% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- NavBar -->
    {% include 'partials/_navbar.html' %}
    <div class="container">

          {% block content %}{% endblock %}

    </div>
  </body>
</html>

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
  <div class="card-body">
    <h1>Bem-vindo</h1>
    <p>Este é um exemplo de aplicação Django</p>
    <a class="btn btn-dark" href="{% url 'enquete:index' %}">
        Abrir enquetes</a
      >
  </div>
  </div>
{% endblock %}

templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
	<div class="container">
		<a class="navbar-brand" href="/">Enquetes</a>
	</div>
</nav>

templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
	<div class="col-md-6 m-auto">

		<a class="btn btn-secondary btn-sm mb-3" href="{% url 'enquete:index' %}">Voltar</a>
		<h1 class="text-center mb-3">{{ questao.questao_texto }}</h1>

		{% if error_message %}
		<p class="alert alert-danger">
			<strong>{{ error_message }}</strong>
		</p>
		{% endif %}

		<form action="{% url 'enquete:vote' questao.id %}" method="post">
			{% csrf_token %}
			{% for choice in questao.choice_set.all %}
				<div class="form-check">
					<input
						type="radio"
						name="choice"
						class="form-check-input"
						id="choice{{ forloop.counter }}"
						value="{{ choice.id }}"
					/>
					<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
					>
				</div>
			{% endfor %}
			<input type="submit" value="Votar" class="btn btn-success btn-lg btn-block mt-4" />
		</form>
	</div>
</div>
{% endblock %}

templates/polls/index.html
{% extends 'base.html' %} 
{% block content %} 
  <h1 class="text-center mb-3">Enquetes</h1>
  {% if latest_question_list %}
    {% for questao in latest_question_list %}
      <div class="card mb-3">
        <div class="card-body">
          <p class="lead">{{ questao.questao_texto }}</p>
          <a href="{% url 'enquete:detalhes' questao.id %}" class="btn btn-primary btn-sm">Vote agora</a>
          <a href="{% url 'enquete:resultados' questao.id %}" class="btn btn-secondary btn-sm">Resultados</a>
        </div>
      </div>
    {% endfor %}
  {% else %}
    <p>No polls available</p>
  {% endif %}
{% endblock %}

templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<script src="https://cdn.zingchart.com/zingchart.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<div class="row">
	<div class="col-md-6 m-auto">

		<h1 class="mb-5 text-center">{{ questao.questao_texto }}</h1>

		<ul class="list-group mb-5">
			{% for choice in questao.choice_set.all %}
			<li class="list-group-item">
				{{ choice.choice_text }}  <span class="badge badge-success float-right">{{ choice.votos }} voto{{ choice.votos | pluralize }}</span>
			</li>
			{% endfor %}
		</ul>

		<a class="btn btn-secondary" href="{% url 'enquete:index' %}">Voltar</a>
		<a class="btn btn-dark" href="{% url 'enquete:detalhes' questao.id %}">Votar</a>
	</div>
</div>
<br>
<div id="myChart"></div>

<script>
	var state = {
		'items':[],
		'values':[],
	}

	var objId = "{{questao.id}}"
	var dataURL = `/enquete/resultadodata/${objId}`

	$.ajax({
		method:'GET',
		url: dataURL,
		success:function(response){
			console.log('RESPONSE:', response)
			for (var i in response){

				var key = Object.keys(response[i])[0]
				var value = Object.values(response[i])[0]

				state.items.push(key)
				state.values.push(value)
			}

			console.log('STATE:', state)
			executarChart()
		}
	})

	function executarChart() {
		var chartData = {
			"type":"bar",
			"title": {
				"text": "Gráfico de votos"
			},
			"scale-x":{
				"values":state.items
			},
			"series":[
				{
					"values":state.values
				}
			]
		}
		zingchart.render({
		id: "myChart",
		data: chartData,
		});
	}

</script>
{% endblock %}